[speedster.testbench]
workspace = "test_project"
description = "Testbench configuration file for extraction"
testbench = "/Users/dasdias/Documents/SoftwareProjects/speedsterpy/speedsterpy/spdstrlib/resources/temp/testbench"
output = "/Users/dasdias/Documents/SoftwareProjects/speedsterpy/speedsterpy/spdstrlib/resources/temp/testbench/output"
